@startuml AuthorizerPackage class

abstract class AuthorizerPackage {
    +createToken()
    +verifyToken()
    +parseSession()
    +getSessionModelName()
    +getSessionModelImport()
    +authorizer()
    +generatePolicy()
}

@enduml